version: "3.9"
services:
  mongo_db:
    container_name: yolo_db
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

# This is the backend service #
  backend:
    container_name: yolo_backend
    build: ./backend
    image: karwega/yolo_backend:v.0.0.1
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/yol
    environment:
      PORTS: 5000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: yolomy
    
    depends_on:
      - mongo_db

# This is the client service #
  client:
    container_name: yolo_client
    build: ./client
    image: karwega/yolo_client
    tty: true
    ports:
      - 3000:3000
    environment:
      PORTS: 3000
    depends_on:
      - backend

volumes:
  mongo_db: {}
