version: "3.9"
services:
  mongo_db:
    container_name: yolo_db
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  backend:
    container_name: yolo_backend
    build: ./backend
    image: karwega/yolo_backend
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      PORTS: 5000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: yolomy
    depends_on:
      - mongo_db

  client:
    container_name: yolo_client
    build: ./client
    image: karwega/yolo_client
    ports:
      - 3000:3000
    environment:
      PORTS: 3000
    depends_on:
      - backend

volumes:
  mongo_db: {}
