apiVersion: v1
kind: Service
metadata:
  name: yoloclient-svc
  namespace: default
  labels:
    app: client-app
spec:
  type: LoadBalancer
  selector:
    app: client-app
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000